---
- hosts: webservers
  become: true
  tasks:
    - name: Install Packages
      apt:
        name: Install apache2
        state: present

    - name: staring apache2 Service
      service:
        name: apache2
        state: started

    - name: Add Firewall Rule
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Deploying Static Website
      copy:
        src: index.html
        dest: /var/www/html/
...
